name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.0
  package_info_plus: ^9.0.0
  provider: ^6.1.2
  intl: ^0.20.2
  fl_chart: ^1.1.1
  vibration: ^3.1.4
  confetti: ^0.8.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/screen.png
    - assets/avatars/
    - assets/sounds/
